name: Auto format code with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run prettier
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn prettier
